color = "Always"
enum_discrim_align_threshold = 100
format_code_in_doc_comments = true
# format_strings = true
match_block_trailing_comma = false
# max_width = 80
# reorder_impl_items = true
# struct_field_align_threshold = 200
wrap_comments = true
imports_granularity='Crate'
imports_layout='Vertical'
