pub mod shift_by_immediate;
pub mod add_subtract_register;
pub mod add_subtract_immediate;
pub mod add_subtract_compare_move_immediate;
pub mod data_processing_register;
pub mod special_data_processing;
pub mod branch_exchange_instruction_set;
pub mod load_from_literal_pool;
pub mod load_store_register_offset;
pub mod load_store_word_byte_immediate_offset;
pub mod load_store_halfword_immediate_offset;
pub mod load_store_to_from_stack;
pub mod add_to_sp_or_pc;
pub mod load_store_multiple;
pub mod conditional_branch;
pub mod software_interrupt;
pub mod unconditional_branch;

// MISSING: Miscellaneous
